### ISSUE TITLE
API issue after installing iHRIS with docker

### ISSUE THREAD

**Issue by ApostleDreSong** [iHRIS/iHRIS#469]
I have deployed iHRIS with docker-compose. I think the baseURL for the backend service is not correct. Axios is making calls to http://localhost:3000. Please, see the attached screenshot and advice.

<img width="1728" alt="Screenshot 2023-09-20 at 07 21 52" src="https://github.com/iHRIS/iHRIS/assets/18594373/3efaac54-1d5c-4cae-a61b-15cc93193478">

**Comment by nobertmn** [comment]
From the image I am seeing, you have the system correctly installed, otherwise you wouldn't be able to see the whole of that blue navigation menu on the left. I think there is an issue with one of the links to a page on that navigation that is breaking the system and needs debugging. Let me look into it and get back to you.
